# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34e23c4fca2ecef1970f75f2a298849076d1ce2961eb8bb9c2c111c74da71796f2db88e03a9ab918705babe3205f7fa4583e215442db2b39d3b73bdc366215e3

test:
  secret_key_base: a5fb0ec2565a809f91c6684249b2841a78700fee35e4d16c03eb711f1cd7425284f9440ffd915c94141f2ea5e9606edcd6666f83e4c56610ab426e7d78aa9b95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
